server {
    listen 80;
    server_name unknown.98.89.177.122.nip.io;

    root /home/ubuntu/unknown-/apps/web/dist;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
