server {
    listen 80;
    server_name unknown.98.89.177.122.nip.io;

    location ^~ /.well-known/acme-challenge/ {
        root /home/ubuntu/unknown-/apps/web/dist;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name unknown.98.89.177.122.nip.io;

    ssl_certificate /etc/letsencrypt/live/unknown.98.89.177.122.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/unknown.98.89.177.122.nip.io/privkey.pem;

    root /home/ubuntu/unknown-/apps/web/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
